name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
  packging:
    runs-on: ubuntu-latest

    needs:
      - build
    steps:
      - run: cargo install cargo-deb
      - uses: actions/checkout@v2
      - run: ls -la
      - run: pwd
      - name: DEB packaging
        run: cargo deb