name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build Artifacts
      run: cd doh; cargo build --release
    - uses: actions/upload-artifact@v2
      with:
          name: doh.so
          path: target/release/libnss_doh.so
  packging:
    runs-on: ubuntu-latest

    needs:
      - build
    steps:
      - run: cargo install cargo-deb
      - name: DEB packaging
        run: cargo deb