name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release
  packging:
    runs-on: ubuntu-latest

    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: DEB packaging
        run: |
         apt-get update -qq
         apt-get install -y -qq devscripts build-essential debhelper lintian dh-make
         mk-build-deps --install --remove --tool "apt-get -y -qq"
         dpkg-buildpackage -us -uc -b
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/debian/doh_0.1.0-1_amd64.deb